steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/opplus-cloud-352011/cloudrun', '.']

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/opplus-cloud-352011/cloudrun']

  # Step 3: Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrun'
      - '--image'
      - 'gcr.io/opplus-cloud-352011/cloudrun'
      - '--region'
      - 'europe-southwest1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
images:
  - 'gcr.io/$PROJECT_ID/cloudrun'